services:
  s-mongodb:
    image: mongo:8.2
    container_name: c-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db_product_service
    volumes:
      - mongo-data:/data/db
    networks:
      - microservices-tutorial-net

volumes:
  mongo-data:
    name: mongo-data

networks:
  microservices-tutorial-net:
    name: microservices-tutorial-net
